
export const myAppsData = [
    {
        appId: '1',
        appName: 'Application Name',
        securityToDoCount: 10,
        VulnerabilityHighCount: 20,
        VulnerabilityMediumCount: 10,
        VulnerabilityLowCount: 4,
    },
    {
        appId: '2',
        appName: 'Application Name',
        securityToDoCount: 10,
        VulnerabilityHighCount: 20,
        VulnerabilityMediumCount: 10,
        VulnerabilityLowCount: 4,
    },
    {
        appId: '3',
        appName: 'Application Name',
        securityToDoCount: 10,
        VulnerabilityHighCount: 20,
        VulnerabilityMediumCount: 10,
        VulnerabilityLowCount: 4,
    },
    {
        appId: '4',
        appName: 'Application Name ApplicationName',
        securityToDoCount: 10,
        VulnerabilityHighCount: 20,
        VulnerabilityMediumCount: 10,
        VulnerabilityLowCount: 4,
    },
    {
        appId: '5',
        appName: 'Application Name ApplicationNameApplicationName',
        securityToDoCount: 10,
        VulnerabilityHighCount: 20,
        VulnerabilityMediumCount: 10,
        VulnerabilityLowCount: 4,
    },
    {
        appId: '6',
        appName: 'ApplicationName',
        securityToDoCount: 10000,
        VulnerabilityHighCount: 20,
        VulnerabilityMediumCount: 10,
        VulnerabilityLowCount: 4,
    },
    {
        appId: '7',
        appName: 'ApplicationName',
        securityToDoCount: 99,
        VulnerabilityHighCount: 20,
        VulnerabilityMediumCount: 10,
        VulnerabilityLowCount: 4,
    },
    {
        appId: '8',
        appName: 'Application Name ApplicationNameApplicationName ApplicationNameApplicationName',
        securityToDoCount: 10,
        VulnerabilityHighCount: 20,
        VulnerabilityMediumCount: 10,
        VulnerabilityLowCount: 4,
    },
    {
        appId: '9',
        appName: 'Application Name ApplicationNameApplicationName',
        securityToDoCount: 10,
        VulnerabilityHighCount: 5000,
        VulnerabilityMediumCount: 3545,
        VulnerabilityLowCount: 584,
    },
    {
        appId: '10',
        appName: 'Application Name ApplicationNameApplicationName',
        securityToDoCount: 10,
        VulnerabilityHighCount: 5000,
        VulnerabilityMediumCount: 3545,
        VulnerabilityLowCount: 584,
    },
];
