export const mockAppInfoPageResponse: any = {
  content: [
    {
      id: 1,
      projectId: 1,
      name: 'scp-api',
      description: null,
      repo: 'https://github.com/WeiJiLab/scp-api',
      branch: 'master',
      username: 'test',
      password: '1',
      repoType: 'GIT',
      codePath: '/',
      workdir: null,
      createdAt: '2022-11-08T17:27:47+08:00',
      updatedAt: '2022-11-08T22:03:34+08:00',
    },
  ],
  pageable: {
    sort: { empty: true, sorted: false, unsorted: true },
    offset: 0,
    pageNumber: 0,
    pageSize: 10,
    paged: true,
    unpaged: false,
  },
  last: true,
  totalPages: 1,
  totalElements: 1,
  first: true,
  size: 10,
  number: 0,
  sort: { empty: true, sorted: false, unsorted: true },
  numberOfElements: 1,
  empty: false,
}
